name: Update

on: 
  workflow_dispatch:
  schedule:
    - cron: 00 20 * * *

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: 设置帐户
        run: git config --global user.name '00575' && git config --global user.email 'xixiaaijia@gmail.com'

      - name: 拉取
        run: |
          git clone --depth 1 https://github.com/immortalwrt/immortalwrt -b openwrt-18.06-k5.4 new
        
      - name: 复制整理
        run: | 
          cp -rf new/include/kernel-version.mk ./include/kernel-version.mk
          rm -rf new
          
      - name: 添加文件到暂存区
        run: git add .
             
      - name: 暂存区全部文件替换工作区
        run: git checkout .

      - name: 提交
        run: git commit -am '内核版本变动'

      - name: 更新
        run: git push
